# Generated by Django 2.1 on 2018-09-06 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKeySampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.SampleModel')),
            ],
        ),
    ]
