# Generated by Django 2.1 on 2018-09-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_foreignkeysamplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManyToManyChildModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyParentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='manytomanychildmodel',
            name='manyToManyParentParentModel',
            field=models.ManyToManyField(to='sampleapp.ManyToManyParentModel'),
        ),
    ]
